# Set name of workflow in GitHub Actions
name: CD

# Only run this workflow on push to main
on:
  push:
    branches:
      - main

# Define jobs within the workflow
jobs:
  # Define a job
  cd:
    # Run this job on Ubuntu
    runs-on: ubuntu-latest

    # Only run this job if the commit message doesn't contain "[skip ci]"
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"

    # Define steps within the job
    steps:
      # Check out the source code
      - name: Checkout Code
        uses: actions/checkout@v2 # https://github.com/actions/checkout
        with:
          # fetch the entire git history
          fetch-depth: "0"

      # Setup NodeJS
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      # Install dependencies
      - name: Install Dependencies
        uses: bahmutov/npm-install@v1

      # Check if the library builds
      - name: Build Library
        run: npm run build

      # Check if the Storybook builds
      - name: Build Storybook
        run: npm run build-storybook

      # Authenticate with npm registry
      - name: Authenticate with Registry
        run: |
          yarn logout
          echo "@topplethenun:registry=http://registry.npmjs.org/" > .npmrc
          echo "registry=http://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc
          npm whoami

      # Create GitHub release
      - name: Create Release
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
